/** @type {import('tailwindcss').Config} */
module.exports = {
  // Uses the user's OS preference by default (matches your requested example)
  darkMode: 'media',
  content: ['./public/index.html', './src/**/*.{js,jsx,ts,tsx}'],
  safelist: [
    {
      // Allows dynamic token usage like: bg-primary-500 / text-typography-900 / border-outline-200 etc.
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|warning|error|success|info|typography|outline|background|shimmer)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|muted|light|dark)/,
    },
  ],
  theme: {
    extend: {
      // IMPORTANT:
      // These colors are driven by CSS variables defined in `src/index.css`.
      // The variables are based on colors already in this project (your existing Tailwind colors + Bootstrap-ish system colors).
      colors: {
        primary: {
          0: 'rgb(var(--color-primary-0) / <alpha-value>)',
          50: 'rgb(var(--color-primary-50) / <alpha-value>)',
          100: 'rgb(var(--color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900) / <alpha-value>)',
          950: 'rgb(var(--color-primary-950) / <alpha-value>)',
        },
        secondary: {
          0: 'rgb(var(--color-secondary-0) / <alpha-value>)',
          50: 'rgb(var(--color-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--color-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--color-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--color-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--color-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--color-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--color-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--color-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--color-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--color-secondary-900) / <alpha-value>)',
          950: 'rgb(var(--color-secondary-950) / <alpha-value>)',
        },
        warning: {
          0: 'rgb(var(--color-warning-0) / <alpha-value>)',
          50: 'rgb(var(--color-warning-50) / <alpha-value>)',
          100: 'rgb(var(--color-warning-100) / <alpha-value>)',
          200: 'rgb(var(--color-warning-200) / <alpha-value>)',
          300: 'rgb(var(--color-warning-300) / <alpha-value>)',
          400: 'rgb(var(--color-warning-400) / <alpha-value>)',
          500: 'rgb(var(--color-warning-500) / <alpha-value>)',
          600: 'rgb(var(--color-warning-600) / <alpha-value>)',
          700: 'rgb(var(--color-warning-700) / <alpha-value>)',
          800: 'rgb(var(--color-warning-800) / <alpha-value>)',
          900: 'rgb(var(--color-warning-900) / <alpha-value>)',
          950: 'rgb(var(--color-warning-950) / <alpha-value>)',
        },
        error: {
          0: 'rgb(var(--color-error-0) / <alpha-value>)',
          50: 'rgb(var(--color-error-50) / <alpha-value>)',
          100: 'rgb(var(--color-error-100) / <alpha-value>)',
          200: 'rgb(var(--color-error-200) / <alpha-value>)',
          300: 'rgb(var(--color-error-300) / <alpha-value>)',
          400: 'rgb(var(--color-error-400) / <alpha-value>)',
          500: 'rgb(var(--color-error-500) / <alpha-value>)',
          600: 'rgb(var(--color-error-600) / <alpha-value>)',
          700: 'rgb(var(--color-error-700) / <alpha-value>)',
          800: 'rgb(var(--color-error-800) / <alpha-value>)',
          900: 'rgb(var(--color-error-900) / <alpha-value>)',
          950: 'rgb(var(--color-error-950) / <alpha-value>)',
        },
        success: {
          0: 'rgb(var(--color-success-0) / <alpha-value>)',
          50: 'rgb(var(--color-success-50) / <alpha-value>)',
          100: 'rgb(var(--color-success-100) / <alpha-value>)',
          200: 'rgb(var(--color-success-200) / <alpha-value>)',
          300: 'rgb(var(--color-success-300) / <alpha-value>)',
          400: 'rgb(var(--color-success-400) / <alpha-value>)',
          500: 'rgb(var(--color-success-500) / <alpha-value>)',
          600: 'rgb(var(--color-success-600) / <alpha-value>)',
          700: 'rgb(var(--color-success-700) / <alpha-value>)',
          800: 'rgb(var(--color-success-800) / <alpha-value>)',
          900: 'rgb(var(--color-success-900) / <alpha-value>)',
          950: 'rgb(var(--color-success-950) / <alpha-value>)',
        },
        info: {
          0: 'rgb(var(--color-info-0) / <alpha-value>)',
          50: 'rgb(var(--color-info-50) / <alpha-value>)',
          100: 'rgb(var(--color-info-100) / <alpha-value>)',
          200: 'rgb(var(--color-info-200) / <alpha-value>)',
          300: 'rgb(var(--color-info-300) / <alpha-value>)',
          400: 'rgb(var(--color-info-400) / <alpha-value>)',
          500: 'rgb(var(--color-info-500) / <alpha-value>)',
          600: 'rgb(var(--color-info-600) / <alpha-value>)',
          700: 'rgb(var(--color-info-700) / <alpha-value>)',
          800: 'rgb(var(--color-info-800) / <alpha-value>)',
          900: 'rgb(var(--color-info-900) / <alpha-value>)',
          950: 'rgb(var(--color-info-950) / <alpha-value>)',
        },
        typography: {
          0: 'rgb(var(--color-typography-0) / <alpha-value>)',
          50: 'rgb(var(--color-typography-50) / <alpha-value>)',
          100: 'rgb(var(--color-typography-100) / <alpha-value>)',
          200: 'rgb(var(--color-typography-200) / <alpha-value>)',
          300: 'rgb(var(--color-typography-300) / <alpha-value>)',
          400: 'rgb(var(--color-typography-400) / <alpha-value>)',
          500: 'rgb(var(--color-typography-500) / <alpha-value>)',
          600: 'rgb(var(--color-typography-600) / <alpha-value>)',
          700: 'rgb(var(--color-typography-700) / <alpha-value>)',
          800: 'rgb(var(--color-typography-800) / <alpha-value>)',
          900: 'rgb(var(--color-typography-900) / <alpha-value>)',
          950: 'rgb(var(--color-typography-950) / <alpha-value>)',
          white: '#ffffff',
          gray: '#d4d4d4',
          black: '#181718',
        },
        outline: {
          0: 'rgb(var(--color-outline-0) / <alpha-value>)',
          50: 'rgb(var(--color-outline-50) / <alpha-value>)',
          100: 'rgb(var(--color-outline-100) / <alpha-value>)',
          200: 'rgb(var(--color-outline-200) / <alpha-value>)',
          300: 'rgb(var(--color-outline-300) / <alpha-value>)',
          400: 'rgb(var(--color-outline-400) / <alpha-value>)',
          500: 'rgb(var(--color-outline-500) / <alpha-value>)',
          600: 'rgb(var(--color-outline-600) / <alpha-value>)',
          700: 'rgb(var(--color-outline-700) / <alpha-value>)',
          800: 'rgb(var(--color-outline-800) / <alpha-value>)',
          900: 'rgb(var(--color-outline-900) / <alpha-value>)',
          950: 'rgb(var(--color-outline-950) / <alpha-value>)',
          muted: 'rgb(var(--color-outline-muted) / <alpha-value>)',
        },
        background: {
          0: 'rgb(var(--color-background-0) / <alpha-value>)',
          50: 'rgb(var(--color-background-50) / <alpha-value>)',
          100: 'rgb(var(--color-background-100) / <alpha-value>)',
          200: 'rgb(var(--color-background-200) / <alpha-value>)',
          300: 'rgb(var(--color-background-300) / <alpha-value>)',
          400: 'rgb(var(--color-background-400) / <alpha-value>)',
          500: 'rgb(var(--color-background-500) / <alpha-value>)',
          600: 'rgb(var(--color-background-600) / <alpha-value>)',
          700: 'rgb(var(--color-background-700) / <alpha-value>)',
          800: 'rgb(var(--color-background-800) / <alpha-value>)',
          900: 'rgb(var(--color-background-900) / <alpha-value>)',
          950: 'rgb(var(--color-background-950) / <alpha-value>)',
          light: '#fbfbfb',
          dark: '#181719',
        },
        shimmer: {
          base: 'rgb(var(--color-shimmer-base) / <alpha-value>)',
          highlight: 'rgb(var(--color-shimmer-highlight) / <alpha-value>)',
        },
      },
      fontFamily: {
        roboto: ['Roboto', 'sans-serif'],
      },
      fontWeight: {
        extrablack: '950',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
  plugins: [],
}
